name: Kirsten
favicon: null
layout_spectrum: 0.8501168084330857
typography_spectrum: 0.6402923611458391
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6500793509185314
  lightness: 0.9416831787675619
  saturation: 0.6856149756349623
  rhythmicContrast: 0.7696888500358909
purpose: []
